// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7GVS-LOmuv2a9gscs6-t8SgxXPlqPSs',
    appId: '1:544621176227:web:6d5eb759ed13cc7f772616',
    messagingSenderId: '544621176227',
    projectId: 'personal-app-6d04b',
    authDomain: 'personal-app-6d04b.firebaseapp.com',
    storageBucket: 'personal-app-6d04b.firebasestorage.app',
    measurementId: 'G-2S2LMWZ55T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbClKzwIYUo7C3TohCMofxpOs79Y56i4U',
    appId: '1:544621176227:android:7086a545c3432726772616',
    messagingSenderId: '544621176227',
    projectId: 'personal-app-6d04b',
    storageBucket: 'personal-app-6d04b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPixswu2faDLj1VReU47kuCOPFJhMxd_Y',
    appId: '1:544621176227:ios:6a0d9131402ba09b772616',
    messagingSenderId: '544621176227',
    projectId: 'personal-app-6d04b',
    storageBucket: 'personal-app-6d04b.firebasestorage.app',
    iosBundleId: 'com.example.tenebris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPixswu2faDLj1VReU47kuCOPFJhMxd_Y',
    appId: '1:544621176227:ios:6a0d9131402ba09b772616',
    messagingSenderId: '544621176227',
    projectId: 'personal-app-6d04b',
    storageBucket: 'personal-app-6d04b.firebasestorage.app',
    iosBundleId: 'com.example.tenebris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF7GVS-LOmuv2a9gscs6-t8SgxXPlqPSs',
    appId: '1:544621176227:web:95497688af8714f0772616',
    messagingSenderId: '544621176227',
    projectId: 'personal-app-6d04b',
    authDomain: 'personal-app-6d04b.firebaseapp.com',
    storageBucket: 'personal-app-6d04b.firebasestorage.app',
    measurementId: 'G-XJ68RXRL9L',
  );
}
